---
- hosts: all
  tasks:
    - name: install apt packages
      sudo: yes
      apt: name={{ item }} state=latest
      with_items:
        - git
        - golang
        - libxml2-dev
        - libxslt-dev
        - python-dev
        # - python-setuptools
        - python-pip

    - name: install python
      sudo: yes
      pip: name={{ item }} state=latest
      with_items:
        - hexlet

    # - shell: docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter creates=/usr/local/bin/nsenter
